language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_script:
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - composer self-update
  - composer install --no-interaction
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi

script: bin/kahlan --coverage=3 --clover=clover.xml

after_success:
  - "if [ $(phpenv version-name) = '5.6' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - "if [ $(phpenv version-name) = '5.6' ]; then php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'; fi"

env:
  global:
    secure: MMmYMUlPQDqQxX0lhQcTrqa2LEfngneGlC4qcllIPlE4eXIUYKSWZDpos7jUR2Ey1eybcyGKm8gYrTrRkrS1Yy5kUd3aMv/NTqVyLt/PEvcFt7kqT+jeaNVQ4+U5U3ym/x9Krxcz5hMb7crw9XkV23qxDLjvFfB92yFRcyHskF/aQtBlzOsY9s0eBJD/QVPsUA+eUdag3fNY4+zFBKfTsKMy+PGYrX7JQzaYROryqOVggfE9oylG5i51FkTlcwx1Vb8ZS3lUfE3/H0ZNVY1zUgF+CUnrPn9qIimCtc2CRhQxR4MkCfADPsFLuFsu7pa/WouE8b+8udIDZK+PZEb43g4M1+GquPtUsudZjTwt8BN0bHBZvj1ZeupiH2tGMhzcwcl23rayyQvC3dzGYMC7fKqOpTLT0OVZdccmUcG7HNVhUJ28wRXuG5HCF2188DdoXf8B6Lc0AvtViuFkRLcY0BOeuNBu7baRQf6ueln7cEB9WSNQhNw0VtisCA1F77wAqu7sq8I4wDLUirk+RfqzCWY+37YkQ3T6jQ92KeXUDiuI7pNeQFyMWF/FzasmhZyEYwkCSlooAU1pm1BtkfCP3IGXdm0zxYBmkqaPjPlfSWT7hwv1AV5V+HoWRS3xXK7QP/g9CpCT7t0Y/IyaJFooBHLfO9YdEZGBCxd9LEQ/6Lk=
